/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_errno_NativeErrno_ErrnoMessage */

#ifndef _Included_com_serial4j_core_errno_NativeErrno_ErrnoMessage
#define _Included_com_serial4j_core_errno_NativeErrno_ErrnoMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_errno_NativeErrno_ErrnoMessage
 * Method:    getMessageFromStdErrno
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_serial4j_core_errno_NativeErrno_00024ErrnoMessage_getMessageFromStdErrno
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
