/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class electrostatic4j_NativeLibrary */

#ifndef _Included_electrostatic4j_NativeLibrary
#define _Included_electrostatic4j_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     electrostatic4j_NativeLibrary
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_electrostatic4j_NativeLibrary_open
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
