/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_filesystem_AbstractFilesystem */

#ifndef _Included_com_serial4j_core_filesystem_AbstractFilesystem
#define _Included_com_serial4j_core_filesystem_AbstractFilesystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_filesystem_AbstractFilesystem
 * Method:    isExistential
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_filesystem_AbstractFilesystem_isExistential
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
